# config/secrets.py

# Gemini
secrets:
  GEMINI_API_KEY: "AIzaSyDKkmkNj2KyMLllE8TVrzb0OJlOGImV00I"
#GEMINI_API_KEY = "AIzaSyDKkmkNj2KyMLllE8TVrzb0OJlOGImV00I"

# OR for OpenAI
#OPENAI_API_KEY = "your-openai-api-key"